= Welcome to ThoughtSpot Preview Documentation
:page-layout: home

++++
<div class="intro">
<p class="intro-text">This site is designed for customers to view draft documentation for the upcoming ThoughtSpot Cloud release. The documentation in this site is subject to change up until the release reaches general availability (GA).

To access this site, you must have a user account. For more information, email <a href="mailto:docs@thoughtspot.com?subject=Access request for preview documentation site">ThoughtSpot Documentation</a>.</p>
</div>
++++
++++
<style>

.intro {
  /* background-color: lightblue; */
  /* padding: 20px; */
  border-radius: 8px;
}

.intro-text {
  font-size: 1.1em;
  color: #666;
}

@media screen and (min-width: 1216px) {
 .intro {
    text-align: center;
  }
}

@media screen and (min-width: 375px) {
    .intro {
        text-align: left;
        margin-left: 3px;
    }
}

button#btn-login {
    width: 110px !important;
    height: 40px;
    font-size: 16px !important;
    font-family: 'Optimo-Plain', sans-serif !important;
    color: white !important;
    height: 43px !important;
    border: 1px solid !important;
    border-radius: 2.2857142857rem !important;
    background: #2770ef !important;
    padding: 0 1.7142857143rem !important;
    border-color: initial !important;
    box-shadow: none !important;
    line-height: 1.4285714286 !important;
}

.home p {
    /* margin: 0; */
    color: #444;
    margin-top: 20px;
    font-family: 'Optimo-Plain', sans-serif;
    margin-bottom: 20px;
    margin-left: 10%;
    margin-right: 10%;
    font-size: 16px;
}

</style>

<div class="auth-parent" style="margin: 0 auto;"></div>
++++
