= Welcome to ThoughtSpot Preview Documentation
:page-layout: home

++++
<div class="intro">
<p class="intro-text">This site is designed for customers to view draft documentation for the upcoming ThoughtSpot Cloud release. The documentation in this site is subject to change up until the release reaches general availability (GA).</p>
<br>
<p class="intro-text">To access this site, you must have a user account. For more information, email <a href="mailto:docs@thoughtspot.com?subject=Access request for preview documentation site">ThoughtSpot Documentation</a>.</p>
</div>
++++
ifdef::preview[]
This content is for preview site only.

So much content in this section, I'd get confused reading the source without the closing `ifdef` directive.

It isn't necessary for short blocks, but if you are conditionally including a section it may be something worth considering.

Other readers reviewing your docs source code may go cross-eyed when reading your source docs if you don't.
endif::preview[]
++++
<style>

@media screen and (min-width: 1216px) {
    .home h1.page {
        font-size: 1.8rem;
        margin-top: 3.5rem;
        text-align: center;
    }
}

@media screen and (min-width: 375px) {
    .home #preamble, .home h1.page {
        text-align: center !important;
        margin-left: 13px;
    }
}

.intro {
  /* background-color: lightblue; */
  /* padding: 20px; */
  border-radius: 8px;
}

.intro-text {
  font-size: 1.1em !important;
  color: #666 !important;
  line-height: 1.5em;
}

@media screen and (min-width: 1216px) {
 .intro {
    text-align: left !important;
  }
}

@media screen and (min-width: 375px) {
    .intro {
        text-align: left !important;
        margin-left: 0px !important;
    }
}

button#btn-login {
    width: 110px !important;
    height: 40px;
    font-size: 16px !important;
    font-family: 'Optimo-Plain', sans-serif !important;
    color: white !important;
    height: 43px !important;
    border: 1px solid !important;
    border-radius: 2.2857142857rem !important;
    background: #2770ef !important;
    padding: 0 1.7142857143rem !important;
    border-color: initial !important;
    box-shadow: none !important;
    line-height: 1.4285714286 !important;
}

.home p {
    /* margin: 0; */
    color: #444;
    margin-top: 20px;
    font-family: 'Optimo-Plain', sans-serif;
    margin-bottom: 20px;
    margin-left: 10%;
    margin-right: 10%;
    font-size: 16px;
}

</style>

<div class="auth-parent" style="margin: 0 auto;"></div>
++++
