= {blank}
:page-layout: home

++++
<div class="title">Welcome to ThoughtSpot Preview Documentation</div>
<div class="intro">
<p class="intro-text">This site provides draft documentation for the upcoming ThoughtSpot Cloud release. The documentation in this site is subject to change up until this release reaches general availability (GA).</p>
<p class="intro-text">To access this site, you must have a user account. For more information, email <a href="mailto:docs@thoughtspot.com?subject=Access request for preview documentation site">ThoughtSpot Documentation</a>.</p>
</div>
<style>

@media screen and (min-width: 1216px) {
    .home h1.page {
        font-size: 1.8rem;
        margin-top: 3.5rem;
        text-align: left;
    }
}

@media screen and (min-width: 375px) {
    .home #preamble, .home h1.page {
        text-align: left !important;
        margin-left: 10%;
    }
}

.intro {
  /* background-color: lightblue; */
  /* padding: 20px; */
  border-radius: 8px;
}

.title {
  font-size: 1.8rem;
  margin-top: 3.5rem;
  text-align: left !important;
  margin-left: 10%;
  margin-right: 10%;
  font-family: Optimo-Plain, sans-serif;
  font-weight: 500;
}

div#auth-wrapper {
  justify-content: left !important;
  margin-left: 10% !important;
}

.intro-text {
  font-size: 1.1em !important;
  color: #666 !important;
  line-height: 1.5em;
}

@media screen and (min-width: 1216px) {
 .intro {
    text-align: left !important;
  }
}

@media screen and (min-width: 375px) {
    .intro {
        text-align: left !important;
        margin-left: 0px !important;
    }
}

button#btn-login {
    width: 110px !important;
    height: 40px;
    font-size: 16px !important;
    font-family: 'Optimo-Plain', sans-serif !important;
    color: white !important;
    height: 43px !important;
    border: 1px solid !important;
    border-radius: 2.2857142857rem !important;
    background: #2770ef !important;
    padding: 0 1.7142857143rem !important;
    border-color: initial !important;
    box-shadow: none !important;
    line-height: 1.4285714286 !important;
}

.home p {
    /* margin: 0; */
    color: #444;
    margin-top: 20px;
    font-family: 'Optimo-Plain', sans-serif;
    margin-bottom: 20px;
    margin-left: 10%;
    margin-right: 10%;
    font-size: 16px;
}

</style>

<div class="auth-parent" style="margin: 0 auto;"></div>
++++
