= Welcome to ThoughtSpot Preview Documentation
:page-layout: home

This site is designed for customers to view draft documentation for the upcoming ThoughtSpot Cloud release. The documentation in this site is subject to change up until the release is rolled out to all customers.

To access this site, you must have a user account. For more information, email mailto:docs@thoughtspot.com[ThoughtSpot Documentation].
++++
<style>

button#btn-login {
    width: 10% !important;
    font-size: 16px !important;
    font-family: 'Optimo-Plain', sans-serif !important;
    color: white !important;
    height: 43px !important;
    border: 1px solid !important;
    border-radius: 2.2857142857rem !important;
    background: #2770ef !important;
    padding: 0 1.7142857143rem !important;
    border-color: initial !important;
    box-shadow: none !important;
    line-height: 1.4285714286 !important;
}

.home p {
    /* margin: 0; */
    color: #444;
    margin-top: 20px;
    font-family: 'Optimo-Plain', sans-serif;
    margin-bottom: 20px;
    margin-left: 200px;
    margin-right: 200px;
    font-size: 16px;
}

</style>

<div class="auth-parent" style="margin: 0 auto;"></div>
++++
